### PR TITLE
deployment for python3

### PR DESCRIPTION
**Pull request by mneedham**

### CODE REVIEW

**Comment by jexp** [comment]
@mneedham @Mogztter will we still need those scripts? if so we should take Marks python3 update in.

**Comment by Mogztter** [comment]
The scripts are using `python2` explicitly but if these changes are backward compatible then we could merge them and use `python` instead. [Python 2 is EOL](https://www.python.org/doc/sunset-python-2/) so we should definitely move to Python 3 but if we can avoid a breaking change that would be nice.

**Comment by Mogztter** [comment]
I port @mneedham code on the master branch in #82

**Comment by Mogztter** [comment]
It can be closed, now that #82 is merged.
Thanks @mneedham for the initial work :+1:

**Pull request closed without merging**
