### PR TITLE
resolves #92 add Mixpanel tracking code

### LINKED ISSUE #92: Add Mixpanel tracking code
Use an API to publish an event to a list of providers. For instance, Mixpanel, Intercom, Google Analytics...

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #92

### CODE REVIEW

**Comment by Mogztter** [comment]
@spgandhi I can see incoming data in "Data Management" > "Live View". I've published this change at https://neo4j.com/graphacademy/online-training/applied-algos-dev/ (private page).

**Comment by spgandhi** [comment]
When I click on logout, I see this error in the console. Also, what events should I check in mixpanel to verify its working fine? Also, has this been set up on the module pages for this course or just the landing page?

Screen Shot 2020-07-03 at 9 43 50 PM

**Comment by spgandhi** [comment]
I am able to see `GRAPH_ACADEMY_REGISTER` event in Mixpanel. So the setup looks fine. If you can look into the above bug and set up it up on the module pages as well, then we can make be sure that it's working there as well.

**Comment by Mogztter** [comment]
> When I click on logout, I see this error in the console. Also, what events should I check in mixpanel to verify its working fine?

Apparently the "Maximum call stack size exceeded" can happen when Mixpanel is loaded more than once. I remember now that Mixpanel is already loaded by the WordPress template so we don't need to load it in the `enrollment.js` script.

https://community.mixpanel.com/sending-data-to-mixpanel-11/maximum-call-stack-size-exceeded-102

> Also, has this been set up on the module pages for this course or just the landing page?

Just for the enrollment page for now, I will add it to the course pages.

**Comment by spgandhi** [comment]
[Add Mixpanel Tracking](https://trello.com/c/TDtORnTW/76-add-mixpanel-tracking)

**Comment by spgandhi** [comment]
Just so that you know, the module pages use `Clean Slate` wordpress template which does not load the WP header. So it won't include mixpanel.

**Comment by Mogztter** [comment]
Then I don't really know, maybe this is related to GTM:

>  In the case of GTM implementations, we recommend placing the Mixpanel snippet on the page directly if possible to ensure it loads properly instead of using GTM to load the Mixpanel library. That will prevent it from loading it multiple times on the same page, to prevent that "Maximum call stack size exceeded" problem, and also ensures it will load before any of your track calls.

I believe we are using GTM but I'm not sure if we are loading Mixpanel from GTM or if we are sending Mixpanel events through Google Tag Manager.

I cannot reliably reproduce this issue, do you?

**Comment by spgandhi** [comment]
We do use GTM to load mixpanel on the neo4j.com website. What I would recommend is we install Tag Manager on the module pages. We should have done it long back because it loads the cookie banner and other important stuff that should go on all pages. Here is the GTM snippet 

Paste this code as high in the <head> of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WK23PSS');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening <body> tag:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WK23PSS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by ElaineRosenberg** [comment]
I do not see any errors on logout.

**Comment by Mogztter** [comment]
> Mixpanel via TagManager has been removed from the online training pages

@Mogztter reminder to rebase and deploy this feature again to test if Mixpanel is now working as expected.

**Pull request merged**
